version: "3.1"
services:
  db:
    image: mariadb:10.6.2
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_USER: jensmemes
      MARIADB_PASSWORD: snens
      MARIADB_DATABASE: jensmemes
    
  adminer:
    image: adminer
    ports:
      - 8080:8080
