kind: pipeline
type: docker
name: release
steps:
    - name: release-linux
      image: rust
      commands:
          - apt update
          - cargo build --release -v
    - name: publish
      image: plugins/gitea-release
      settings:
          base_url: https://tilera.xyz/git
          api_key:
              from_secret: gitea_token
          note: CHANGELOG.md
          title: tag-${DRONE_TAG}
          files:
              - target/release/jmserver
      when:
          event: tag
      depends_on:
          - release-linux